Create netlify.md
onecompiler/cheatsheets pull request #144
Opened 2022-10-03 15:22 UTC by shashank1623

added another cloud related application . that is free for use..

2022-10-03 15:59 UTC, onecompiler-ops requested changes

2022-10-03 15:59 UTC, onecompiler-ops commented on netlify.md
> +created:  7 February 2014
date format is wrong please use yyyy-mm-dd

2022-10-03 15:59 UTC, onecompiler-ops commented
Could you please add cli commands too ?

2022-10-03 16:23 UTC, shashank1623 commented
> Could you please add cli commands too ?

for netlify supports drag and drop of your project dir and netlfiy algo will host your application. for the time being you merge my pr after that i will updated that if i i found cli commands

2022-10-03 16:25 UTC, shashank1623 commented
errors resolved now merge it!

2022-10-03 16:27 UTC, onecompiler-ops commented
What is the value this cheat sheet adds? Why some one would refer to it?

2022-10-03 16:28 UTC, shashank1623 commented
in order if you want cli commands then i'm adding it. give a day

2022-10-03 16:42 UTC, shashank1623 commented
added the cli commands

2022-10-04 05:37 UTC, onecompiler-ops commented
<img width="1305" alt="Screenshot 2022-10-04 at 11 06 55 AM" src="https://user-images.githubusercontent.com/71093215/193742571-9830c89a-9be1-4f4a-a248-44ffe66e2fed.png">
Markdown formatting broken, please fix it

2022-10-04 07:43 UTC, shashank1623 commented
issue solved!

2022-10-04 09:21 UTC, onecompiler-ops approved these changes

2022-10-04 09:21 UTC, merged