Improved OOPS Concept
onecompiler/cheatsheets pull request #232
Opened 2022-10-05 17:48 UTC by tanuj1811

Solved Issue ( ID : #196 )

2022-10-05 18:58 UTC, onecompiler-ops requested changes

2022-10-05 18:58 UTC, onecompiler-ops commented on java.md
> -`/* */` - multi line comment
Why these are removed?

2022-10-05 19:16 UTC, tanuj1811 reviewed
Approved Changes

2022-10-05 19:17 UTC, tanuj1811 commented
What should I do?
Make a new PR

2022-10-05 19:26 UTC, onecompiler-ops commented
do rebase

2022-10-05 19:38 UTC, tanuj1811 commented
Hey @onecompiler-ops ,
Can you review again.

2022-10-06 13:42 UTC, tanuj1811 commented
Hey @onecompiler-ops ,
You haven't merged this PR yet. Is something wrong?

2022-10-07 09:13 UTC, onecompiler-ops commented
This is a very specific use-case, and does not belong in Cheat Sheets, please write this as a post instead here https://onecompiler.com/posts

2022-10-07 09:28 UTC, tanuj1811 commented
I just improved the quality of sheet by adding points or examples. 
Post is like blog. Both are different. You should read again. These changes more understandable and knowledable.

Thank you

2022-10-07 09:37 UTC, onecompiler-ops requested changes

2022-10-07 09:37 UTC, onecompiler-ops commented on java.md
> +Example : Consider the Paytm app, we don't know how money is being transferred from one account to another within a second, all we know is we can make payment using the app.
Please use global examples

2022-10-07 09:38 UTC, onecompiler-ops commented
@tanuj1811 cheat sheets are supposed to be precise, please avoid lengthy explanations. Keep them simple and easy with meaningful code snippets. 
In Tutorials we can add in-depth details

2022-10-07 12:24 UTC, tanuj1811 commented
@onecompiler-ops , 
I updated the example. Now the example is more concise and simple. You can review it.

Thanks

2022-10-07 13:22 UTC, onecompiler-ops commented
@tanuj1811 can you have a look at the Tutorials repo? Your content better suites there

2022-11-08 06:16 UTC, closed without merging