Added Lists and Keys in React cheatsheet
onecompiler/cheatsheets pull request #385
Opened 2022-10-11 09:40 UTC by kanishbodhwani

## Lists and keys in React  
> - Rendering Multiple components through **Lists**.
> - Short and concise.  

### Below is the screenshot 

<img width="995" alt="Screenshot 2022-10-11 at 3 02 23 PM" src="https://user-images.githubusercontent.com/64742906/195054164-4d174153-ecab-43b0-abbd-e97b525d64b9.png">

2022-10-15 10:35 UTC, onecompiler-ops requested changes
revert changes to new-cheat-sheet-request.md

2022-10-16 17:07 UTC, kanishbodhwani commented
Do I have to make a new cheat sheet just for Lists and Keys in React ?

2022-10-17 12:53 UTC, onecompiler-ops requested changes

2022-10-17 12:53 UTC, onecompiler-ops commented on .github/ISSUE_TEMPLATE/new-cheat-sheet-request.md
> -name: New Cheat Sheet Request
revert this

2022-10-17 18:09 UTC, closed without merging