Nestedlist
onecompiler/cheatsheets pull request #475
Opened 2022-10-20 19:01 UTC by SimranLahrani842

List within a list.
useful-when you want to create a matrix or want a list within list of different data types

2022-10-20 19:05 UTC, SimranLahrani842 commented
You can insert ,pop, del the elements of a list within a list using indexes.

2022-10-21 07:20 UTC, onecompiler-ops requested changes

2022-10-21 07:20 UTC, onecompiler-ops commented on c.md
> +##use of fflush()
Fix markdown issues

2022-10-21 09:24 UTC, SimranLahrani842 commented on c.md
> +##use of fflush()
fixed as per required.

2022-10-22 03:41 UTC, onecompiler-ops approved these changes

2022-10-22 03:42 UTC, merged

2022-10-22 06:59 UTC, SimranLahrani842 commented
Sir,please add the respected labels of hacktober2022,accepted,etc.

2022-10-22 09:47 UTC, onecompiler-ops commented
@SimranLahrani842 added