Information is added regarding the list of header files in cpp.md
onecompiler/cheatsheets pull request #92
Opened 2022-10-02 05:15 UTC by jaisinha

I have added the 10 most crucial and fundamental header files

2022-10-02 05:26 UTC, onecompiler-ops requested changes

2022-10-02 05:26 UTC, onecompiler-ops commented on cpp.md
> +## Header Files
This is advanced concept, so can you move it to the bottom of the page, also please format the content as markdown table

2022-10-02 05:29 UTC, jaisinha commented
I am not able to preview the cpp.md...can tell me how to do it?

2022-10-02 06:04 UTC, closed without merging

2022-10-03 05:36 UTC, jaisinha commented
can you pl see the changes